/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-05-15 05:21:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class feedback_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Registration Page</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"Styles/feedinStyle.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<img src=\"images\\logo.png\" class=\"logo\" >\r\n");
      out.write("\r\n");
      out.write("<a href=\"profile.jsp\">\r\n");
      out.write("<img src=\"images\\user.png\" class=\"user\">\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("    <h1 class=\"logo_topic\">FreshCraze</h1>\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar\">\r\n");
      out.write("        <a href=\"HomePageAL.jsp\">Home</a>\r\n");
      out.write("        <a href=\"index.jsp\">Logout</a>\r\n");
      out.write("        <a href=\"feedbackLog.jsp\">Feedback</a>\r\n");
      out.write("        <span></span>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("<hr class=\"topic_line\">\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("<h1 class = \"head\">Feedback</h1>\r\n");
      out.write("\r\n");
      out.write("<form name=\"feedbackForm\" action=\"feedback\" method=\"post\" onsubmit=\"return validateForm()\">\r\n");
      out.write("	<table class = \"table\">\r\n");
      out.write("     \r\n");
      out.write("   		<tbody>\r\n");
      out.write("		<tr class=\"active-row\">\r\n");
      out.write("			<td>Name:</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"name\" placeholder=\"Enter your name\" ></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>Contact Email:</td>\r\n");
      out.write("			<td><input type=\"email\" name=\"email\" placeholder=\"Enter your email\" ></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr class=\"active-row\">\r\n");
      out.write("			<td>Subject:</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"subject\" placeholder=\"Enter feedback subject\" ></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>Message:</td>\r\n");
      out.write("			<td><textarea name=\"message\" rows=\"5\" cols=\"20\" placeholder=\"Write your valuable feedback\" ></textarea></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr class=\"active-row\">\r\n");
      out.write("			<td>Do you satisfy with our service:</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"question\" placeholder=\"Yes or No\" ></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("    </tbody>\r\n");
      out.write("	</table>\r\n");
      out.write("	<input type=\"submit\" name=\"submit\" class=\"sub\" value=\"Submit\"><br><br><br>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function validateForm() {\r\n");
      out.write("        var name = document.forms[\"feedbackForm\"][\"name\"].value;\r\n");
      out.write("        var email = document.forms[\"feedbackForm\"][\"email\"].value;\r\n");
      out.write("        var subject = document.forms[\"feedbackForm\"][\"subject\"].value;\r\n");
      out.write("        var message = document.forms[\"feedbackForm\"][\"message\"].value;\r\n");
      out.write("        var satisfaction = document.forms[\"feedbackForm\"][\"question\"].value;\r\n");
      out.write("\r\n");
      out.write("        if (name == \"\" || email == \"\" || subject == \"\" || message == \"\" || satisfaction == \"\") {\r\n");
      out.write("            alert(\"All fields must be filled out\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        var emailPattern = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\r\n");
      out.write("        if (!emailPattern.test(email)) {\r\n");
      out.write("            alert(\"Please enter a valid email address\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (satisfaction.toLowerCase() !== \"yes\" && satisfaction.toLowerCase() !== \"no\") {\r\n");
      out.write("            alert(\"Please enter 'Yes' or 'No' for satisfaction\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        return true;\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr class=\"footer_line\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("    <a href=\"link\" target=\"_blank\">\r\n");
      out.write("    <button type=\"button\" class=\"help_button\">Help and Support</button>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"fb_icon\">\r\n");
      out.write("        <a href=\"https://www.facebook.com/\" target=\"_blank\"><img src=\"images/facebook.png\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"insta_icon\">\r\n");
      out.write("        <a href=\"https://www.instagram.com/\" target=\"_blank\"><img src=\"images/insta.png\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"twitt_icon\">\r\n");
      out.write("        <a href=\"https://www.twitter.com/\" target=\"_blank\"><img src=\"images/Twitter.png\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"yt_icon\">\r\n");
      out.write("        <a href=\"https://www.youtube.com/\" target=\"_blank\"><img src=\"images/yt.png\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"contacts\">\r\n");
      out.write("    <h1 class=\"link\">www.freshcraze.lk</h1>\r\n");
      out.write("    <h1>Hotline: +94 225 225 25 / +94 225 225 35</h1>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
